# Generated by Django 5.1.4 on 2025-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Image",
            field=models.ImageField(upload_to="products"),
        ),
    ]
