# Generated by Django 5.1.4 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Image",
            field=models.URLField(),
        ),
    ]
