# Generated by Django 5.1.4 on 2024-12-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('NULL', 'Null'), ('Dog', 'Dog'), ('Cat', 'Cat')], default='NULL', max_length=4)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Description', models.TextField()),
                ('Brand', models.CharField(max_length=20)),
                ('Weight', models.CharField(max_length=20)),
                ('Stock', models.IntegerField()),
                ('Ratin', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Image', models.ImageField(upload_to='products/')),
                ('Ingredients', models.ManyToManyField(to='api.ingredients')),
            ],
        ),
    ]
