# Generated by Django 5.1.4 on 2024-12-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredients_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Ratin',
            new_name='Rating',
        ),
    ]
