# Generated by Django 5.1.4 on 2024-12-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ingredients_products_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
