# Generated by Django 5.1.4 on 2024-12-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ingredients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
