# Generated by Django 5.1.4 on 2024-12-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_products_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
