# Generated by Django 5.1.4 on 2024-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('Select', 'Select'), ('Dog', 'Dog'), ('Cat', 'Cat')], default='Select', max_length=6),
        ),
    ]
