# Generated by Django 5.1.4 on 2024-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='products',
            name='Ingredient',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
