# Generated by Django 5.1.4 on 2024-12-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_products_ingredient_delete_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
