# Generated by Django 5.1.4 on 2024-12-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_is_delete_products_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Ingredient',
            field=models.JSONField(default=list),
        ),
    ]
