# Generated by Django 5.1.4 on 2024-12-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_products_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Ingredient',
            field=models.JSONField(default=list),
        ),
    ]
