# Generated by Django 5.1.4 on 2024-12-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_products_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Rating',
        ),
        migrations.AddField(
            model_name='products',
            name='product_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Ingredient',
            field=models.JSONField(default=list),
        ),
    ]
