# Generated by Django 5.1.4 on 2025-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_orders_orde_user_id_a87c6f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Shipping", "Shipping"),
                    ("Cancelled", "Cancelled"),
                    ("Pending", "Pending"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
