# Generated by Django 5.1.4 on 2025-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_updated_at_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Shipped", "Shipped"),
                    ("Cancelled", "Cancelled"),
                    ("Pending", "Pending"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
